# Generated by Django 5.1.2 on 2025-03-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='varification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
