# Generated by Django 5.1.2 on 2025-03-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gust.login')),
            ],
        ),
    ]
