# Generated by Django 5.1.2 on 2025-03-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gust', '0002_login_varification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='police_station_reject',
            fields=[
                ('station_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gust.login')),
            ],
        ),
        migrations.CreateModel(
            name='police_station_varify',
            fields=[
                ('station_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gust.login')),
            ],
        ),
    ]
