# Generated by Django 5.1.2 on 2025-03-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police_station_varify',
            name='login_id',
        ),
        migrations.DeleteModel(
            name='police_station_reject',
        ),
        migrations.DeleteModel(
            name='police_station_varify',
        ),
    ]
