# Generated by Django 5.1.2 on 2025-03-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police_station', '0005_remove_police_station_registration_varification_status'),
        ('web_admin', '0002_remove_police_station_varify_login_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='police_station_varified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varified_stations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='police_station.police_station_registration')),
            ],
        ),
    ]
