# Generated by Django 5.1.2 on 2025-03-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='police_station_varified',
        ),
    ]
