# Generated by Django 5.1.2 on 2025-03-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_station_registration',
            name='varification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
